# 이 워크플로는 다양한 파이썬 버전으로 파이썬 종속성을 설치하고 테스트를 실행하며 보푸라기를 사용합니다.
# 자세한 내용은 다음을 참조하세요: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

이름: 디스코드 알림봇 

온:
 스케쥴: # UTC+9 기준 3시 실행
 - 크론: "0 18 * * *"

작업:
 빌드:

 실행 중: 우분투-latest
 전략.:
 실패 속도의: 거짓의
 매트릭스:
 파이썬 버전: ["3.9", "3.10", "3.11"]

 단계:
    - uses: actions/checkout@v4
-  이름: Python ${matrix.python-version}을 설정합니다.
 용도: 작업/setup-python@v3
 와 함께:
 파이썬 버전: ${{matrix.python 버전}}
-  이름: 종속성 설치
 달려.: |
 python -m pip 설치 --업그레이드 pip
 파이썬 - m 핍 설치 플레이크8 파이테스트
 [ -f 요구 사항인 경우].txt]; 그런 다음 pip 설치 -r 요건을 충족합니다.txt; fi
-  이름: 박편 8이 포함된 보푸라기
 달려.: |
 # 파이썬 구문 오류 또는 정의되지 않은 이름이 있는 경우 빌드 중지
 flake8 --count --select=E9,F63,F7,F82 --show-source --통계
 # 0 종료는 모든 오류를 경고로 처리합니다. GitHub 편집기의 너비는 127자입니다.
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
